// Copyright (c) 2025 Admenri. All rights reserved.
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool and should not edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//
// $hash=2a280c078306f4620d7dcaec498f89d9abd938a9$
//

#ifndef ACF_INCLUDE_CAPI_ACF_REGISTRATION_CAPI_H_
#define ACF_INCLUDE_CAPI_ACF_REGISTRATION_CAPI_H_
#pragma once

#include "include/capi/acf_base_capi.h"
#include "include/internal/acf_scoped_refptr.h"

#ifdef __cplusplus
extern "C" {
#endif

///
/// Generic callback structure used for managing the lifespan of a registration.
///
typedef struct _acf_registration_t {
  ///
  /// Base structure.
  ///
  acf_base_ref_counted_t base;
} acf_registration_t;

#ifdef __cplusplus
}
#endif

#endif  // ACF_INCLUDE_CAPI_ACF_REGISTRATION_CAPI_H_
