// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=b9f013d8d54c74d8baa0edfa3318dad38818cb01$
//

#ifndef ACF_CTOCPP_BROWSER_CTOCPP_H_
#define ACF_CTOCPP_BROWSER_CTOCPP_H_
#pragma once

#include <vector>

#include "include/acf_browser.h"
#include "include/acf_devtools_observer.h"
#include "include/acf_environment.h"
#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_profile.h"
#include "include/acf_registration.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_devtools_observer_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_registration_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfBrowserCToCpp
    : public AcfCToCppRefCounted<AcfBrowserCToCpp, AcfBrowser, acf_browser_t> {
 public:
  AcfBrowserCToCpp();
  virtual ~AcfBrowserCToCpp();

  // AcfBrowser methods.
  bool IsSame(AcfRefPtr<AcfBrowser> that) override;
  AcfRefPtr<AcfDictionaryValue> GetExtraInfo() override;
  AcfRefPtr<AcfEnvironment> GetEnvironment() override;
  void Close(bool force) override;
  void ResumeLoadingBrowser() override;
  AcfWindowHandle GetWindowHandle() override;
  bool IsValid() override;
  bool CanGoBack() override;
  bool CanGoForward() override;
  void GoBack() override;
  void GoForward() override;
  void Reload(bool ignore_cache) override;
  void Stop() override;
  bool IsLoading() override;
  void LoadURL(const AcfString& url,
               const AcfString& referrer_url,
               acf_referrer_policy_t referrer_policy,
               acf_transition_type_t transition_type,
               const AcfString& extra_header) override;
  AcfString GetURL() override;
  AcfString GetTitle() override;
  AcfString GetFavicon() override;
  void Focus() override;
  void SetVisible(bool visible) override;
  bool GetVisible() override;
  AcfRefPtr<AcfProfile> GetProfile() override;
  size_t GetFrameCount() override;
  void GetFrameIdentifiers(std::vector<int64>& identifiers) override;
  void GetFrameNames(std::vector<AcfString>& names) override;
  AcfRefPtr<AcfFrame> GetFrame(int64 identifier) override;
  AcfRefPtr<AcfFrame> GetFrame(const AcfString& name) override;
  AcfRefPtr<AcfFrame> GetMainFrame() override;
  void SetSettings(const AcfBrowserSettings& settings) override;
  void SetAudioMuted(bool muted) override;
  bool IsAudioMuted() override;
  void ToggleDevtools() override;
  void OpenTaskManager() override;
  void RaiseFindBar() override;
  void ZoomPage(acf_zoom_type_t zoom_type) override;
  void ToggleExtensionsMenu() override;
  void ToggleDownloadUIForWindow() override;
  void ToggleMediaRouterBubble() override;
  void SendKeyEvent(const AcfKeyEvent& event) override;
  void SendMouseClickEvent(const AcfMouseEvent& event,
                           MouseButtonType type,
                           bool mouseUp,
                           int clickCount) override;
  void SendMouseMoveEvent(const AcfMouseEvent& event, bool mouseLeave) override;
  void SendMouseWheelEvent(const AcfMouseEvent& event,
                           int deltaX,
                           int deltaY) override;
  int AddDocumentStartJavaScript(
      const AcfString& script,
      const std::vector<AcfString>& allow_origins) override;
  void RemoveDocumentStartJavaScript(int script_id) override;
  void AddWebMessageHostFactory(
      AcfRefPtr<AcfWebMessageFactory> factory,
      const AcfString& js_object_name,
      const std::vector<AcfString>& allow_origins) override;
  void RemoveWebMessageHostFactory(const AcfString& js_object_name) override;
  void AddFunctionRegisterHostFactory(
      AcfRefPtr<AcfFunctionFactory> factory,
      const AcfString& js_object_name,
      const AcfString& function_name,
      const std::vector<AcfString>& allow_origins) override;
  void RemoveFunctionRegisterHostFactory(
      const AcfString& js_object_name) override;
  void SendDevToolsMessage(const void* message, size_t message_size) override;
  AcfRefPtr<AcfRegistration> AddDevToolsMessageObserver(
      AcfRefPtr<AcfDevToolsMessageObserver> observer) override;
  void ImeSetComposition(const AcfString& text,
                         const std::vector<AcfCompositionUnderline>& underlines,
                         const AcfRange& replacement_range,
                         const AcfRange& selection_range) override;
  void ImeCommitText(const AcfString& text,
                     const AcfRange& replacement_range,
                     int relative_cursor_pos) override;
  void ImeFinishComposingText(bool keep_selection) override;
  void ImeCancelComposition() override;
  void CaptureScreenshot(bool fast_encoded,
                         bool from_surface,
                         AcfRefPtr<AcfCompleteValueHandler> handler) override;
  void SetContextProfile(AcfRefPtr<AcfValue> context_profile) override;
};

#endif  // ACF_CTOCPP_BROWSER_CTOCPP_H_
