// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=bfb55501eeeb2fa49d3856017c6198d01ba3a84c$
//

#ifndef ACF_CTOCPP_COOKIE_CTOCPP_H_
#define ACF_CTOCPP_COOKIE_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_profile.h"
#include "include/acf_values.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfCookieCToCpp
    : public AcfCToCppRefCounted<AcfCookieCToCpp, AcfCookie, acf_cookie_t> {
 public:
  AcfCookieCToCpp();
  virtual ~AcfCookieCToCpp();

  // AcfCookie methods.
  AcfString GetName() override;
  AcfString GetValue() override;
  AcfString GetDomain() override;
  AcfString GetPath() override;
  bool IsHttponly() override;
  bool IsSecure() override;
  AcfCookieSameSite GetSameSite() override;
  AcfCookiePriority GetPriority() override;
  double GetCreation() override;
  double GetExpiry() override;
  double GetLastAccess() override;
  double GetLastUpdate() override;
};

#endif  // ACF_CTOCPP_COOKIE_CTOCPP_H_
