// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=2872f64aaec30765002cd01e687eae41c2ce7a1c$
//

#ifndef ACF_CTOCPP_DOMDOCUMENT_CTOCPP_H_
#define ACF_CTOCPP_DOMDOCUMENT_CTOCPP_H_
#pragma once

#include "include/acf_dom.h"
#include "include/capi/acf_dom_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfDOMDocumentCToCpp : public AcfCToCppRefCounted<AcfDOMDocumentCToCpp,
                                                        AcfDOMDocument,
                                                        acf_domdocument_t> {
 public:
  AcfDOMDocumentCToCpp();
  virtual ~AcfDOMDocumentCToCpp();

  // AcfDOMDocument methods.
  Type GetType() override;
  AcfRefPtr<AcfDOMNode> GetDocument() override;
  AcfString GetTitle() override;
  AcfString GetBaseURL() override;
};

#endif  // ACF_CTOCPP_DOMDOCUMENT_CTOCPP_H_
