// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=997c351a59e4b5be81883592eb29853ac4aff0e3$
//

#ifndef ACF_CTOCPP_DOMNODE_CTOCPP_H_
#define ACF_CTOCPP_DOMNODE_CTOCPP_H_
#pragma once

#include "include/acf_dom.h"
#include "include/capi/acf_dom_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfDOMNodeCToCpp
    : public AcfCToCppRefCounted<AcfDOMNodeCToCpp, AcfDOMNode, acf_domnode_t> {
 public:
  AcfDOMNodeCToCpp();
  virtual ~AcfDOMNodeCToCpp();

  // AcfDOMNode methods.
  Type GetType() override;
  AcfString GetName() override;
  AcfString GetValue() override;
  AcfString GetAsMarkup() override;
  int GetChildNodeCount() override;
  AcfRefPtr<AcfDOMNode> GetChildNode(int index) override;
  AcfString GetElementTagName() override;
  bool HasElementAttributes() override;
  bool HasElementAttribute(const AcfString& attrName) override;
  AcfString GetElementAttribute(const AcfString& attrName) override;
  void GetElementAttributes(AttributeMap& attrMap) override;
  AcfString GetElementInnerText() override;
  AcfRect GetElementBounds() override;
};

#endif  // ACF_CTOCPP_DOMNODE_CTOCPP_H_
