// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f0ed57c1a7c0c05afb80a334c0d8abdf3dd091c3$
//

#ifndef ACF_CTOCPP_FRAME_CTOCPP_H_
#define ACF_CTOCPP_FRAME_CTOCPP_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_callback.h"
#include "include/acf_dom.h"
#include "include/acf_frame.h"
#include "include/acf_values.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_dom_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfFrameCToCpp
    : public AcfCToCppRefCounted<AcfFrameCToCpp, AcfFrame, acf_frame_t> {
 public:
  AcfFrameCToCpp();
  virtual ~AcfFrameCToCpp();

  // AcfFrame methods.
  bool IsValid() override;
  bool IsSame(AcfRefPtr<AcfFrame> object) override;
  AcfRefPtr<AcfFrame> GetParent() override;
  AcfRefPtr<AcfBrowser> GetBrowser() override;
  AcfString GetURL() override;
  AcfString GetName() override;
  int64 GetIdentifier() override;
  bool IsMain() override;
  void ExecuteJavascript(
      const AcfString& script,
      const AcfString& url,
      AcfRefPtr<AcfExecuteJavascriptCallback> handler) override;
  void GetSource(AcfRefPtr<AcfStringVisitor> visitor) override;
  void GetDOMDocument(AcfRefPtr<AcfDOMDocumentCallback> visitor) override;
  void QuerySelectorAll(const AcfString& selector,
                        AcfRefPtr<AcfDOMNodeCallback> visitor) override;
};

#endif  // ACF_CTOCPP_FRAME_CTOCPP_H_
