// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=0387c9e8c6e817f7657c3dccfc2ae348790fb2e7$
//

#include "libacf_dll/ctocpp/java_script_dialog_callback_ctocpp.h"

// VIRTUAL METHODS - Body may be edited by hand.

void AcfJavaScriptDialogCallbackCToCpp::Continue(bool success,
                                                 const AcfString& user_input) {
  acf_java_script_dialog_callback_t* _struct = GetStruct();
  if (ACF_MEMBER_MISSING(_struct, cont)) {
    return;
  }

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Unverified params: user_input

  // Execute
  _struct->cont(_struct, success, user_input.GetStruct());
}

// CONSTRUCTOR - Do not edit by hand.

AcfJavaScriptDialogCallbackCToCpp::AcfJavaScriptDialogCallbackCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

AcfJavaScriptDialogCallbackCToCpp::~AcfJavaScriptDialogCallbackCToCpp() {}

template <>
acf_java_script_dialog_callback_t*
AcfCToCppRefCounted<AcfJavaScriptDialogCallbackCToCpp,
                    AcfJavaScriptDialogCallback,
                    acf_java_script_dialog_callback_t>::
    UnwrapDerived(AcfWrapperType type, AcfJavaScriptDialogCallback* c) {
  return nullptr;
}

template <>
AcfWrapperType
    AcfCToCppRefCounted<AcfJavaScriptDialogCallbackCToCpp,
                        AcfJavaScriptDialogCallback,
                        acf_java_script_dialog_callback_t>::kWrapperType =
        WT_JAVA_SCRIPT_DIALOG_CALLBACK;
