// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=e915a4e61759b50df62b389eeff0427fd88ef9f8$
//

#ifndef ACF_CTOCPP_LOGIN_DELEGATE_CTOCPP_H_
#define ACF_CTOCPP_LOGIN_DELEGATE_CTOCPP_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_devtools_observer.h"
#include "include/acf_environment.h"
#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_profile.h"
#include "include/acf_registration.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_devtools_observer_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_registration_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfLoginDelegateCToCpp
    : public AcfCToCppRefCounted<AcfLoginDelegateCToCpp,
                                 AcfLoginDelegate,
                                 acf_login_delegate_t> {
 public:
  AcfLoginDelegateCToCpp();
  virtual ~AcfLoginDelegateCToCpp();

  // AcfLoginDelegate methods.
  void Continue(const AcfString& user_name, const AcfString& password) override;
  void Cancel() override;
};

#endif  // ACF_CTOCPP_LOGIN_DELEGATE_CTOCPP_H_
