// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=6cf88606e08bbc9738be77db9e4f610cc7465cad$
//

#ifndef ACF_CTOCPP_PERMISSION_PROMPT_CALLBACK_CTOCPP_H_
#define ACF_CTOCPP_PERMISSION_PROMPT_CALLBACK_CTOCPP_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_devtools_observer.h"
#include "include/acf_environment.h"
#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_profile.h"
#include "include/acf_registration.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_devtools_observer_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_registration_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfPermissionPromptCallbackCToCpp
    : public AcfCToCppRefCounted<AcfPermissionPromptCallbackCToCpp,
                                 AcfPermissionPromptCallback,
                                 acf_permission_prompt_callback_t> {
 public:
  AcfPermissionPromptCallbackCToCpp();
  virtual ~AcfPermissionPromptCallbackCToCpp();

  // AcfPermissionPromptCallback methods.
  void Continue(acf_permission_request_result_t result) override;
};

#endif  // ACF_CTOCPP_PERMISSION_PROMPT_CALLBACK_CTOCPP_H_
