// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=9c2ba984973c7efb21e61e04cc898c1d121eea6f$
//

#ifndef ACF_CTOCPP_POST_DATA_ELEMENT_CTOCPP_H_
#define ACF_CTOCPP_POST_DATA_ELEMENT_CTOCPP_H_
#pragma once

#include "include/acf_request.h"
#include "include/capi/acf_request_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfPostDataElementCToCpp
    : public AcfCToCppRefCounted<AcfPostDataElementCToCpp,
                                 AcfPostDataElement,
                                 acf_post_data_element_t> {
 public:
  AcfPostDataElementCToCpp();
  virtual ~AcfPostDataElementCToCpp();

  // AcfPostDataElement methods.
  bool IsReadOnly() override;
  void SetToEmpty() override;
  void SetToFile(const AcfString& fileName) override;
  void SetToBytes(size_t size, const void* bytes) override;
  Type GetType() override;
  AcfString GetFile() override;
  size_t GetBytesCount() override;
  size_t GetBytes(size_t size, void* bytes) override;
};

#endif  // ACF_CTOCPP_POST_DATA_ELEMENT_CTOCPP_H_
