// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=5848dea146e76ed851640c1953f6ced266270374$
//

#ifndef ACF_CTOCPP_PROMISE_RESOLVER_CTOCPP_H_
#define ACF_CTOCPP_PROMISE_RESOLVER_CTOCPP_H_
#pragma once

#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_values.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfPromiseResolverCToCpp
    : public AcfCToCppRefCounted<AcfPromiseResolverCToCpp,
                                 AcfPromiseResolver,
                                 acf_promise_resolver_t> {
 public:
  AcfPromiseResolverCToCpp();
  virtual ~AcfPromiseResolverCToCpp();

  // AcfPromiseResolver methods.
  void Resolve(AcfRefPtr<AcfValue> return_value) override;
};

#endif  // ACF_CTOCPP_PROMISE_RESOLVER_CTOCPP_H_
