// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8f1a6dbcebf6c57d4341821be5512bf96d034433$
//

#ifndef ACF_CTOCPP_REGISTRATION_CTOCPP_H_
#define ACF_CTOCPP_REGISTRATION_CTOCPP_H_
#pragma once

#include "include/acf_registration.h"
#include "include/capi/acf_registration_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfRegistrationCToCpp : public AcfCToCppRefCounted<AcfRegistrationCToCpp,
                                                         AcfRegistration,
                                                         acf_registration_t> {
 public:
  AcfRegistrationCToCpp();
  virtual ~AcfRegistrationCToCpp();

  // AcfRegistration methods.
};

#endif  // ACF_CTOCPP_REGISTRATION_CTOCPP_H_
