// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=ac0c5b94dc65ee6acea2a78891a7667f86d4b91c$
//

#ifndef ACF_CTOCPP_RESOURCE_READ_CALLBACK_CTOCPP_H_
#define ACF_CTOCPP_RESOURCE_READ_CALLBACK_CTOCPP_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfResourceReadCallbackCToCpp
    : public AcfCToCppRefCounted<AcfResourceReadCallbackCToCpp,
                                 AcfResourceReadCallback,
                                 acf_resource_read_callback_t> {
 public:
  AcfResourceReadCallbackCToCpp();
  virtual ~AcfResourceReadCallbackCToCpp();

  // AcfResourceReadCallback methods.
  void Continue(int bytes_read) override;
};

#endif  // ACF_CTOCPP_RESOURCE_READ_CALLBACK_CTOCPP_H_
