// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=040aa2187dbb91153b7dbc4b9e0dc384c68c02b1$
//

#ifndef ACF_CTOCPP_URLREQUEST_CTOCPP_H_
#define ACF_CTOCPP_URLREQUEST_CTOCPP_H_
#pragma once

#include "include/acf_environment.h"
#include "include/acf_urlrequest.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_urlrequest_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfURLRequestCToCpp : public AcfCToCppRefCounted<AcfURLRequestCToCpp,
                                                       AcfURLRequest,
                                                       acf_urlrequest_t> {
 public:
  AcfURLRequestCToCpp();
  virtual ~AcfURLRequestCToCpp();

  // AcfURLRequest methods.
  AcfRefPtr<AcfRequest> GetRequest() override;
  AcfRefPtr<AcfURLRequestClient> GetClient() override;
  AcfRefPtr<AcfEnvironment> GetEnvironment() override;
  uint32 GetFlags() override;
  AcfRefPtr<AcfResponse> GetResponse() override;
  void Cancel() override;
};

#endif  // ACF_CTOCPP_URLREQUEST_CTOCPP_H_
