// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8a5daf1dead1e8c1fc883f934b2206ecbdebd843$
//

#ifndef ACF_CTOCPP_WEB_SOCKET_CLIENT_CTOCPP_H_
#define ACF_CTOCPP_WEB_SOCKET_CLIENT_CTOCPP_H_
#pragma once

#include "include/acf_values.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfWebSocketClientCToCpp
    : public AcfCToCppRefCounted<AcfWebSocketClientCToCpp,
                                 AcfWebSocketClient,
                                 acf_web_socket_client_t> {
 public:
  AcfWebSocketClientCToCpp();
  virtual ~AcfWebSocketClientCToCpp();

  // AcfWebSocketClient methods.
  bool IsValid() override;
  AcfRefPtr<AcfWebSocketClientHandler> GetHandler() override;
  void SendMessageTo(acf_websocket_message_routing_t direction,
                     AcfRefPtr<AcfValue> message) override;
  void SendCloseConnectionRequest(
      acf_websocket_message_routing_t direction) override;
};

#endif  // ACF_CTOCPP_WEB_SOCKET_CLIENT_CTOCPP_H_
