// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=72d1f6483ffbaed73f9bc5410e4b13f2d1611224$
//

#ifndef ACF_CTOCPP_WEB_MESSAGE_PROXY_CTOCPP_H_
#define ACF_CTOCPP_WEB_MESSAGE_PROXY_CTOCPP_H_
#pragma once

#include "include/acf_frame.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "libacf_dll/ctocpp/ctocpp_ref_counted.h"

// Wrap a C structure with a C++ class.
// This class may be instantiated and accessed wrapper-side only.
class AcfWebMessageProxyCToCpp
    : public AcfCToCppRefCounted<AcfWebMessageProxyCToCpp,
                                 AcfWebMessageProxy,
                                 acf_web_message_proxy_t> {
 public:
  AcfWebMessageProxyCToCpp();
  virtual ~AcfWebMessageProxyCToCpp();

  // AcfWebMessageProxy methods.
  void PostWebMessage(const WebMessage& message) override;
  bool IsInBackForwardCache() override;
};

#endif  // ACF_CTOCPP_WEB_MESSAGE_PROXY_CTOCPP_H_
