// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=312c2f0ab55db9c86bf91e8855f93a2c84f41632$
//

#ifndef ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_devtools_observer.h"
#include "include/acf_environment.h"
#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_profile.h"
#include "include/acf_registration.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_devtools_observer_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_registration_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfBrowserHandlerCppToC
    : public AcfCppToCRefCounted<AcfBrowserHandlerCppToC,
                                 AcfBrowserHandler,
                                 acf_browser_handler_t> {
 public:
  AcfBrowserHandlerCppToC();
  virtual ~AcfBrowserHandlerCppToC();
};

#endif  // ACF_CPPTOC_BROWSER_HANDLER_CPPTOC_H_
