// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=d8d1b1d24907ad88366708a3fff11fa93a8b35aa$
//

#include "libacf_dll/cpptoc/cookie_visitor_cpptoc.h"

#include "libacf_dll/ctocpp/cookie_ctocpp.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

int ACF_CALLBACK cookie_visitor_visit(struct _acf_cookie_visitor_t* self,
                                      acf_cookie_t* cookie,
                                      int count,
                                      int total) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self) {
    return 0;
  }
  // Unverified params: cookie

  // Execute
  bool _retval = AcfCookieVisitorCppToC::Get(self)->Visit(
      AcfCookieCToCpp::Wrap(cookie), count, total);

  // Return type: bool
  return _retval;
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfCookieVisitorCppToC::AcfCookieVisitorCppToC() {
  GetStruct()->visit = cookie_visitor_visit;
}

// DESTRUCTOR - Do not edit by hand.

AcfCookieVisitorCppToC::~AcfCookieVisitorCppToC() {}

template <>
AcfRefPtr<AcfCookieVisitor> AcfCppToCRefCounted<
    AcfCookieVisitorCppToC,
    AcfCookieVisitor,
    acf_cookie_visitor_t>::UnwrapDerived(AcfWrapperType type,
                                         acf_cookie_visitor_t* s) {
  return nullptr;
}

template <>
AcfWrapperType AcfCppToCRefCounted<AcfCookieVisitorCppToC,
                                   AcfCookieVisitor,
                                   acf_cookie_visitor_t>::kWrapperType =
    WT_COOKIE_VISITOR;
