// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=19b84ac85669132cefab5b18f01350664d148740$
//

#ifndef ACF_CPPTOC_DEV_TOOLS_MESSAGE_OBSERVER_CPPTOC_H_
#define ACF_CPPTOC_DEV_TOOLS_MESSAGE_OBSERVER_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_devtools_observer.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_devtools_observer_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfDevToolsMessageObserverCppToC
    : public AcfCppToCRefCounted<AcfDevToolsMessageObserverCppToC,
                                 AcfDevToolsMessageObserver,
                                 acf_dev_tools_message_observer_t> {
 public:
  AcfDevToolsMessageObserverCppToC();
  virtual ~AcfDevToolsMessageObserverCppToC();
};

#endif  // ACF_CPPTOC_DEV_TOOLS_MESSAGE_OBSERVER_CPPTOC_H_
