// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=6e84c10474e34d20365fe6855d2cfefc01d9cb41$
//

#include "libacf_dll/cpptoc/domdocument_callback_cpptoc.h"

#include "libacf_dll/ctocpp/domdocument_ctocpp.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void ACF_CALLBACK
domdocument_callback_on_domresult(struct _acf_domdocument_callback_t* self,
                                  acf_domdocument_t* value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self) {
    return;
  }
  // Unverified params: value

  // Execute
  AcfDOMDocumentCallbackCppToC::Get(self)->OnDOMResult(
      AcfDOMDocumentCToCpp::Wrap(value));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfDOMDocumentCallbackCppToC::AcfDOMDocumentCallbackCppToC() {
  GetStruct()->on_domresult = domdocument_callback_on_domresult;
}

// DESTRUCTOR - Do not edit by hand.

AcfDOMDocumentCallbackCppToC::~AcfDOMDocumentCallbackCppToC() {}

template <>
AcfRefPtr<AcfDOMDocumentCallback> AcfCppToCRefCounted<
    AcfDOMDocumentCallbackCppToC,
    AcfDOMDocumentCallback,
    acf_domdocument_callback_t>::UnwrapDerived(AcfWrapperType type,
                                               acf_domdocument_callback_t* s) {
  return nullptr;
}

template <>
AcfWrapperType AcfCppToCRefCounted<AcfDOMDocumentCallbackCppToC,
                                   AcfDOMDocumentCallback,
                                   acf_domdocument_callback_t>::kWrapperType =
    WT_DOMDOCUMENT_CALLBACK;
