// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7b234b98e65c1be83a5be1b8997f5cb5485a6d76$
//

#ifndef ACF_CPPTOC_DOMDOCUMENT_CALLBACK_CPPTOC_H_
#define ACF_CPPTOC_DOMDOCUMENT_CALLBACK_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_callback.h"
#include "include/acf_dom.h"
#include "include/acf_frame.h"
#include "include/acf_values.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_dom_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfDOMDocumentCallbackCppToC
    : public AcfCppToCRefCounted<AcfDOMDocumentCallbackCppToC,
                                 AcfDOMDocumentCallback,
                                 acf_domdocument_callback_t> {
 public:
  AcfDOMDocumentCallbackCppToC();
  virtual ~AcfDOMDocumentCallbackCppToC();
};

#endif  // ACF_CPPTOC_DOMDOCUMENT_CALLBACK_CPPTOC_H_
