// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=8053e8881dfa45c6a53877ae5bee79746ae96fc8$
//

#ifndef ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_browser.h"
#include "include/acf_callback.h"
#include "include/acf_environment.h"
#include "include/acf_frame.h"
#include "include/acf_profile.h"
#include "include/acf_request.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_browser_capi.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_profile_capi.h"
#include "include/capi/acf_request_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfEnvironmentHandlerCppToC
    : public AcfCppToCRefCounted<AcfEnvironmentHandlerCppToC,
                                 AcfEnvironmentHandler,
                                 acf_environment_handler_t> {
 public:
  AcfEnvironmentHandlerCppToC();
  virtual ~AcfEnvironmentHandlerCppToC();
};

#endif  // ACF_CPPTOC_ENVIRONMENT_HANDLER_CPPTOC_H_
