// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c45de059e7ee548c9975f7da97065cc9d82f4c22$
//

#include "libacf_dll/cpptoc/execute_javascript_callback_cpptoc.h"

#include "libacf_dll/ctocpp/value_ctocpp.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void ACF_CALLBACK execute_javascript_callback_on_execute_result(
    struct _acf_execute_javascript_callback_t* self,
    struct _acf_value_t* value) {
  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  if (!self) {
    return;
  }
  // Unverified params: value

  // Execute
  AcfExecuteJavascriptCallbackCppToC::Get(self)->OnExecuteResult(
      AcfValueCToCpp::Wrap(value));
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

AcfExecuteJavascriptCallbackCppToC::AcfExecuteJavascriptCallbackCppToC() {
  GetStruct()->on_execute_result =
      execute_javascript_callback_on_execute_result;
}

// DESTRUCTOR - Do not edit by hand.

AcfExecuteJavascriptCallbackCppToC::~AcfExecuteJavascriptCallbackCppToC() {}

template <>
AcfRefPtr<AcfExecuteJavascriptCallback>
AcfCppToCRefCounted<AcfExecuteJavascriptCallbackCppToC,
                    AcfExecuteJavascriptCallback,
                    acf_execute_javascript_callback_t>::
    UnwrapDerived(AcfWrapperType type, acf_execute_javascript_callback_t* s) {
  return nullptr;
}

template <>
AcfWrapperType
    AcfCppToCRefCounted<AcfExecuteJavascriptCallbackCppToC,
                        AcfExecuteJavascriptCallback,
                        acf_execute_javascript_callback_t>::kWrapperType =
        WT_EXECUTE_JAVASCRIPT_CALLBACK;
