// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=71599c4e95325598538323b1d2dcf5a3046a24ce$
//

#ifndef ACF_CPPTOC_FUNCTION_FACTORY_CPPTOC_H_
#define ACF_CPPTOC_FUNCTION_FACTORY_CPPTOC_H_
#pragma once

#include "include/acf_frame.h"
#include "include/acf_function_handler.h"
#include "include/acf_values.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_function_handler_capi.h"
#include "include/capi/acf_values_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfFunctionFactoryCppToC
    : public AcfCppToCRefCounted<AcfFunctionFactoryCppToC,
                                 AcfFunctionFactory,
                                 acf_function_factory_t> {
 public:
  AcfFunctionFactoryCppToC();
  virtual ~AcfFunctionFactoryCppToC();
};

#endif  // ACF_CPPTOC_FUNCTION_FACTORY_CPPTOC_H_
