// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=bc922a739bcfad470ac65f9f3dfc87095e628527$
//

#ifndef ACF_CPPTOC_RESOURCE_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_RESOURCE_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfResourceHandlerCppToC
    : public AcfCppToCRefCounted<AcfResourceHandlerCppToC,
                                 AcfResourceHandler,
                                 acf_resource_handler_t> {
 public:
  AcfResourceHandlerCppToC();
  virtual ~AcfResourceHandlerCppToC();
};

#endif  // ACF_CPPTOC_RESOURCE_HANDLER_CPPTOC_H_
