// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=61bff3395ec07c85f27fe8e6b4191cd5571095bd$
//

#ifndef ACF_CPPTOC_RESPONSE_FILTER_CPPTOC_H_
#define ACF_CPPTOC_RESPONSE_FILTER_CPPTOC_H_
#pragma once

#include "include/acf_callback.h"
#include "include/acf_frame.h"
#include "include/acf_resource_request_handler.h"
#include "include/capi/acf_callback_capi.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_resource_request_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfResponseFilterCppToC
    : public AcfCppToCRefCounted<AcfResponseFilterCppToC,
                                 AcfResponseFilter,
                                 acf_response_filter_t> {
 public:
  AcfResponseFilterCppToC();
  virtual ~AcfResponseFilterCppToC();
};

#endif  // ACF_CPPTOC_RESPONSE_FILTER_CPPTOC_H_
