// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=533635e99021c1d571f69b6c8f95852b8482802c$
//

#ifndef ACF_CPPTOC_URLREQUEST_CLIENT_CPPTOC_H_
#define ACF_CPPTOC_URLREQUEST_CLIENT_CPPTOC_H_
#pragma once

#include "include/acf_environment.h"
#include "include/acf_urlrequest.h"
#include "include/capi/acf_environment_capi.h"
#include "include/capi/acf_urlrequest_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfURLRequestClientCppToC
    : public AcfCppToCRefCounted<AcfURLRequestClientCppToC,
                                 AcfURLRequestClient,
                                 acf_urlrequest_client_t> {
 public:
  AcfURLRequestClientCppToC();
  virtual ~AcfURLRequestClientCppToC();
};

#endif  // ACF_CPPTOC_URLREQUEST_CLIENT_CPPTOC_H_
