// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f678653e8a3f8a757049ed95afe6e1a2aaea76f4$
//

#ifndef ACF_CPPTOC_WEB_SOCKET_CLIENT_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_WEB_SOCKET_CLIENT_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_values.h"
#include "include/acf_websocket.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_websocket_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfWebSocketClientHandlerCppToC
    : public AcfCppToCRefCounted<AcfWebSocketClientHandlerCppToC,
                                 AcfWebSocketClientHandler,
                                 acf_web_socket_client_handler_t> {
 public:
  AcfWebSocketClientHandlerCppToC();
  virtual ~AcfWebSocketClientHandlerCppToC();
};

#endif  // ACF_CPPTOC_WEB_SOCKET_CLIENT_HANDLER_CPPTOC_H_
