// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=7968b068048bd0579246131d879f23e4f18fa542$
//

#ifndef ACF_CPPTOC_WEB_MESSAGE_FACTORY_CPPTOC_H_
#define ACF_CPPTOC_WEB_MESSAGE_FACTORY_CPPTOC_H_
#pragma once

#include "include/acf_frame.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfWebMessageFactoryCppToC
    : public AcfCppToCRefCounted<AcfWebMessageFactoryCppToC,
                                 AcfWebMessageFactory,
                                 acf_web_message_factory_t> {
 public:
  AcfWebMessageFactoryCppToC();
  virtual ~AcfWebMessageFactoryCppToC();
};

#endif  // ACF_CPPTOC_WEB_MESSAGE_FACTORY_CPPTOC_H_
