// Copyright (c) 2025 Admenri. All rights reserved.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the ACF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=45b4cd77dec256e823878596b0ee6f6fd22277e8$
//

#ifndef ACF_CPPTOC_WEB_MESSAGE_HANDLER_CPPTOC_H_
#define ACF_CPPTOC_WEB_MESSAGE_HANDLER_CPPTOC_H_
#pragma once

#include "include/acf_frame.h"
#include "include/acf_values.h"
#include "include/acf_web_message_handler.h"
#include "include/capi/acf_frame_capi.h"
#include "include/capi/acf_values_capi.h"
#include "include/capi/acf_web_message_handler_capi.h"
#include "libacf_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class AcfWebMessageHandlerCppToC
    : public AcfCppToCRefCounted<AcfWebMessageHandlerCppToC,
                                 AcfWebMessageHandler,
                                 acf_web_message_handler_t> {
 public:
  AcfWebMessageHandlerCppToC();
  virtual ~AcfWebMessageHandlerCppToC();
};

#endif  // ACF_CPPTOC_WEB_MESSAGE_HANDLER_CPPTOC_H_
